### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by bitflowers** [aave/interface#1664] opened 2023-06-24 13:25 UTC
Transaction failed
![Screenshot_1](https://github.com/aave/interface/assets/99252123/ca81980f-640e-401e-a414-d7743cd2c478)

**Comment by ManicChemist** [comment] 2023-06-24 23:35
I am getting the same error.  I'm using polygon network with ledger live mobile.  Worked fine a few days ago!  I can't get any transactions through

**Comment by Jdecristi** [comment] 2023-06-26 17:29
@foodaka @sakulstra would this have to do with the public urls? It's my first guess but I am unable to reproduce it myself

**Comment by foodaka** [comment] 2023-09-19 08:44
possibly rpc at that time, closing out unless it reappears

**Closed by foodaka** 2023-09-19 08:44 UTC
Labels: bug, new issue
