### ISSUE TITLE
Repay with collateral

### ISSUE THREAD

**Issue by Essah10** [aave/interface#573] opened 2022-03-24 18:13 UTC
Hi guys

With the new UI the user cant repay with his collateral in the ethereum v2 market. He said he can only see it with the classic v2 UI![image](https://user-images.githubusercontent.com/76067798/159982937-f7d1fe82-0df1-4940-95e2-44ff930d0a0f.png)

**Comment by sakulstra** [comment] 2022-03-24 19:11
That's a known issue.

There's a work in progress to port repay with collateral to all markets herehttps://github.com/aave/interface/pull/448 in case someone wants to pick that up.

**Comment by sakulstra** [comment] 2022-04-17 10:00
duplicate of -#638

**Closed by sakulstra** 2022-04-17 10:00 UTC
Labels: feature
