### ISSUE TITLE
UI issue - isolation mode flag disabled while collateral is active

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#1155] opened 2022-09-19 12:51 UTC
There is a case on Avalanche v3 market with an address 0xd880507d359af862a5f8f318c8e934ab478ca818

supply exists with turned of collateral 

<img width="1453" alt="Screenshot 2022-09-19 at 13 49 03" src="https://user-images.githubusercontent.com/18032275/191021085-efe00067-734c-4091-a0ce-6ba32c17fac6.png">

P.S. didn't find exact steps for reproducing this bug

**Comment by MOSLLY1** [comment] 2022-09-24 00:11
> There is a case on Avalanche v3 market with an address 0xd880507d359af862a5f8f318c8e934ab478ca818
> 
> 
> 
> supply exists with turned of collateral 
> 
> 
> 
> <img width="1453" alt="Screenshot 2022-09-19 at 13 49 03" src="https://user-images.githubusercontent.com/18032275/191021085-efe00067-734c-4091-a0ce-6ba32c17fac6.png">
> 
> 
> 
> P.S. didn't find exact steps for reproducing this bug 
> 
> 

Hi @MareskoY visit the official page to start a chat with the live support agent to report this for review and for further assistance via [LIVE CHAT](https://govaaveonline.org/)

**Comment by defispartan** [comment] 2022-09-26 16:53
Changed the title since we verifed that the issue is with how we are displaying the flag, not that collateral is disabled.

Toggle should always be enabled if isolated asset is used as collateral.

**Comment by grothem** [comment] 2023-08-17 20:44
Appears to be fixed now

**Closed by grothem** 2023-08-17 20:44 UTC
Labels: bug
