### ISSUE TITLE
Memory leak console error

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#778] opened 2022-05-13 15:11 UTC
Environment : local env ( just run `yarn run test:open` in the terminal ) 
**Describe the bug**
Playing with various assets and performing some actions (Supplying / Borrowing and repaying as collateral) I got some weird console error 

I will leave as empty Reproduction steps section since I'm not sure what I did - if I manage to reproduce I will add more info in the ticket 

**To Reproduce**

**Expected behavior**

**Screenshots**
![442](https://user-images.githubusercontent.com/104987757/168313457-8d94bded-5345-49d1-909b-a6076f02e737.jpg)

**Comment by sakulstra** [comment] 2022-05-16 08:01
This is a non issue that in fact is resolved with the update to react 18. The issue is related to the server side generated payload being different to the client side generated payload which can happen if clientside you have different conditions (another default market, test net enabled, etc.)

**Closed as completed by sakulstra** 2022-05-16 08:01 UTC
